#!/bin/bash

if [ $# -ne 1 ]; then
	echo "usage: addWebUser DOMAIN"
	exit
fi

VHDOMAIN=$1

if [ $(/usr/local/bin/isDomain "$VHDOMAIN") = "0" ];then
	echo "domain problems"
	exit
fi

VHNAME=$(echo $VHDOMAIN | /usr/local/bin/mkUser)
VHPASS=$(/usr/local/bin/mkPasswd)
echo $VHNAME
echo $VHDOMAIN
echo $VHPASS

read -p "ok? (y) : " OK

if [ $OK != "y" ]; then
echo "exiting"
exit
fi

echo "adding group"
groupadd $VHNAME
echo "done"

echo "adding user and home dir"
useradd -s /bin/bash -g $VHNAME -G www-data -m -d /var/www/homes/$VHNAME -k /etc/skel $VHNAME
mkdir -p /var/www/homes/$VHNAME/.ssh
cat /root/.ssh/authorized_keys > /var/www/homes/$VHNAME/.ssh/authorized_keys
chown $VHNAME:$VHNAME /var/www/homes/$VHNAME/.ssh -Rv
echo "done"

echo "setting user password"
echo $VHNAME:$VHPASS | chpasswd
echo "done"

echo "copying apache config"
cp /usr/local/bin/apache2.template /etc/apache2/sites-available/$VHDOMAIN
echo "done"

echo "changing php.fcgi"
sed -i -e "s/NAME/$VHNAME/g" /var/www/homes/$VHNAME/bin/php.fcgi
echo "done"

echo "changing apache config"
sed -i -e "s/NAME/$VHNAME/g" -e "s/DOMAIN/$VHDOMAIN/g" /etc/apache2/sites-available/$VHDOMAIN
echo "done"

echo "enabling domain in apache"
a2ensite $VHDOMAIN
echo "done"

echo "reloading apache"
/etc/init.d/apache2 force-reload
echo "done"

#echo "fixing permissions on public_html"
#chown www-data:www-data /var/www/homes/$VHNAME/public_html
#echo "done"

echo "setting up stats"
cp /usr/local/bin/logrotate.template /etc/logrotate.d/$VHDOMAIN
sed -i -e "s/DOMAIN/$VHDOMAIN/g" -e "s/USERNAME/$VHNAME/g" /etc/logrotate.d/$VHDOMAIN
htpasswd -bc /var/www/homes/$VHNAME/.htpasswd $VHNAME $VHPASS
cp /usr/local/bin/awstats.conf.template /etc/awstats/awstats.$VHDOMAIN.conf
sed -i -e "s/DOMAIN/$VHDOMAIN/g" -e "s/USERNAME/$VHNAME/g" /etc/awstats/awstats.$VHDOMAIN.conf


###########
# WEBALIZER
#
cp /usr/local/bin/webalizer.conf.template /etc/webalizer/$VHDOMAIN.webalizer.conf
sed -i -e "s/USERNAME/$VHNAME/g" -e "s/DOMAINNAME/$VHDOMAIN/g" /etc/webalizer/$VHDOMAIN.webalizer.conf

# ok we are going to make a mysql account for each web user, why not

/usr/local/bin/addMysqlUser $VHNAME $VHPASS

echo "done"

echo "#################"
echo "user: $VHNAME"
echo "pass: $VHPASS"
echo "domain $VHDOMAIN"
echo "#################"

echo "

New account activated:

##############
user: $VHNAME
pass: $VHPASS
domain: $VHDOMAIN
##############

" | mailx -s "new account $VHDOMAIN activated" zz9plural9zalpha@gmail.com -c root
